### ISSUE TITLE
JSCalendar: Evaluation of `BYWEEKNO` and `BYSETPOS` Properties

### ISSUE THREAD

**Issue by christophercrouzet** [CalConnect/PUBLIC_DRAFTS#18] opened 2020-09-11 22:05 UTC
Hello!

I am having a question regarding the evaluation of recurring rules involving the `BYWEEKNO` and `BYSETPOS` properties.

Please correct me if I'm wrong but, from my understanding, the [JSCalendar specification at section 4.3.2.1](https://datatracker.ietf.org/doc/html/draft-ietf-calext-jscalendar-27#section-4.3.2.1) seems to point that for the following rule

```
FREQ=YEARLY;BYWEEKNO=1,2
DTSTART:20130101T000000
```

the results should be as follows:

```
20130101T000000
20130108T000000
20131231T000000
20140107T000000
...
```

That's cool. However, and once again I might very well be misinterpreting the specification here, it seems that the rule

```
FREQ=YEARLY;BYWEEKNO=1,2;BYSETPOS=1
DTSTART:20130101T000000
```

would result in the following results:

```
20130101T000000
20140107T000000
...
```

When I would instead ‘intuitively’ expect that the first week would be interpreted relatively to the ISO weeks and hence the first result for the year 2014 would in fact fall on the previous year as such:

```
20130101T000000
20131231T000000
...
```

So the question is: am I misunderstanding something? Or is this choice deliberate and these results are expected?

**Comment by dmfs** [comment] 2020-09-11 22:36
I think your interpretation is (unfortunately) correct and I agree that this would be unexpected behavior. [lib-recur](https://github.com/dmfs/lib-recur) returns the [values you expect](http://recurrence-expansion-service.appspot.com/reaas?dtstart=20130101&rrule=FREQ%3DYEARLY%3BBYWEEKNO%3D1%2C2%3BBYSETPOS%3D1&skip=&max_instances=10&expansion_window_end=21000101T000000).

This is certainly an edge case, but it needs to be fixed nevertheless.

**Comment by christophercrouzet** [comment] 2020-09-11 23:00
Hello @dmfs, thank you for getting back to me!

In this case, would it be safe to assume that swapping the frequency from `YEARLY` to `MONTHLY` would also yield the same results (as shown [here](http://recurrence-expansion-service.appspot.com/reaas?dtstart=20130101T000000&rrule=FREQ%3DMONTHLY%3BBYWEEKNO%3D1%2C2%3BBYSETPOS%3D1&skip=&max_instances=100&expansion_window_end=20170101T000000))?

Note: I understand that using the property `BYWEEKNO` with anything else than a `YEARLY` frequency is not allowed by RFC 5545, but in theory there shouldn't be any harm to it? :stuck_out_tongue:

**Comment by dmfs** [comment] 2020-09-11 23:17
Yes, if you ignore that fact that `BYWEEKNO` is illegal with anything but `YEARLY` rules, `MONTHLY` rules would yield the same results.
That is basically because the interval length doesn't matter when you expand by some property that also spans the entire year (as long as you don't skip any intervals).

**Comment by christophercrouzet** [comment] 2020-09-12 01:10
Awesome, thanks for your insights @dmfs!

Also, thanks to whoever worked on the JSCalendar spec, this really helped me out in understanding how a recurring rule implementation would look like in comparison to the ambiguous RFC 5545, and this one issue was the last piece of the puzzle that I needed to fully make sense of it! :+1:

**Comment by christophercrouzet** [comment] 2020-09-13 11:08
FYI, I just made public my attempt at implementing the JSCalendar spec in Python: https://github.com/christophercrouzet/wadu.

**Comment by neilj** [comment] 2020-09-14 00:22
> Also, thanks to whoever worked on the JSCalendar spec, this really helped me out in understanding how a recurring rule implementation would look like in comparison to the ambiguous RFC 5545

Thanks, that was my goal! I'm going to close this issue because it seems like the spec is clear enough and everyone's on the same page.

**Closed as completed by neilj** 2020-09-14 00:22 UTC
